/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "TIA_1.h"
#include "TIA_2.h"
#include "TIA1_in_aliases.h"
#include "TIA1_in.h"
#include "TIA2_in_aliases.h"
#include "TIA2_in.h"
#include "TIA1_out_aliases.h"
#include "TIA1_out.h"
#include "TIA2_out_aliases.h"
#include "TIA2_out.h"
#include "Chart_1.h"
#include "Clock_ADC.h"
#include "DMA_1_dma.h"
#include "Trigger_aliases.h"
#include "Trigger.h"
#include "Clock_Trig.h"
#include "UART_1.h"
#include "Reg_Hab_Adq.h"
#include "SOCo_aliases.h"
#include "SOCo.h"
#include "Opamp_1.h"
#include "OPA_minus_aliases.h"
#include "OPA_minus.h"
#include "OPA_plus_aliases.h"
#include "OPA_plus.h"
#include "ADC_SAR_1.h"
#include "Vref_aliases.h"
#include "Vref.h"
#include "Opamp_2.h"
#include "OPA_out_aliases.h"
#include "OPA_out.h"
#include "isr_Fin_Adq.h"
#include "isr_rx.h"
#include "UART_1_IntClock.h"
#include "ADC_SAR_1_IRQ.h"
#include "ADC_SAR_1_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

